name: Rental Scraper

on:
  push:
    branches:
      - main

  schedule:
    - cron: '30 2 * * *'  # runs daily at 2:30 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
      VESTEDA_USER: ${{ secrets.VESTEDA_USER }}
      VESTEDA_PASSWORD: ${{ secrets.VESTEDA_PASSWORD }}

    steps:
      - name: Checkout code
      
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PATH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python src/rental/process_rental_main.py

      - name: Commit and push results
        run: |
          git config --global user.name 'Lebramjames'
          git config --global user.email 'bramgriffioen98@gmail.com'
          git add data/huren/*.csv
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Amsterdam property data $(date +'%Y-%m-%d')"
            git push origin main
          fi