name: VBT Huren Scraper

on:
  push:
    branches:
      - main

  schedule:
    - cron: '30 2 * * *'  # runs daily at 2:30

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python src/rental/process_rental_main.py

      - name: Commit and push results
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'Lebramjames'
          git config --global user.email 'bramgriffioen98@gmail.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add data/*.csv
          git commit -m "🗓️ Daily VBT Housing Page scrape - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
